server:
  port: 8081

grpc:
  client:
    greeting-service:
      address: static://localhost:9090
      negotiationType: PLAINTEXT

rest:
  greeting-service:
    endpoint: http://localhost:8088
    api:
      greeting: /api/greeting